version: 2.1

executors:
  yarn_update_pr:
    docker:
      - image: dependabot/dependabot-core
        environment:
          PACKAGE_MANAGER: npm_and_yarn
          PROJECT_PATH: risafj/node_image_processor
          BUNDLE_GEMFILE: Gemfile-dependabot

jobs:
  raise_yarn_update_pr:
    executor: yarn_update_pr
    steps:
      - checkout
      - run:
          name: Bundle install inside Dependabot container
          command:
            bundle install -j 3 --path vendor --gemfile=Gemfile-dependabot
      - run:
          name: Execute yarn upgrade script
          command:
            bundle exec ruby ./generic-update-script.rb

workflows:
  version: 2
  yarn_update_pr:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - raise_yarn_update_pr
